-- Generated by tools/build/build-loader.mjs. Edit tools/loader/runtime.lua and shared/Bootstrap.
local LoadingPresentation
local function FinishLoading(Outcome)
    if LoadingPresentation then
        pcall(LoadingPresentation.RequestComplete or LoadingPresentation.Complete, LoadingPresentation, Outcome)
    end
end
local function ObserveLoading(Framework)
    if not LoadingPresentation or LoadingPresentation.ReadyProbe then return end
    local Previous = Framework.Context
    LoadingPresentation.ReadyProbe = function()
        local Context = Framework.Context
        if type(Context) ~= "table" or Context == Previous or Context.Destroyed then return false end
        if type(Context.Startup) == "table" then return Context.Startup.Status == "ready" end
        local Library = type(Context.UI) == "table" and Context.UI.Library
        return type(Library) == "table" and Library.Unloaded ~= true
    end
end
local function RunHub()
local StartupUI = (function()
-- Y Loader UI. Presentation only.
local Modules, Loaded = {}, {}
Modules["Theme"] = function(require)
return {
	Background = Color3.fromRGB(12, 11, 15),
	Surface = Color3.fromRGB(24, 18, 26),
	Border = Color3.fromRGB(48, 38, 49),
	Text = Color3.fromRGB(243, 239, 243),
	Muted = Color3.fromRGB(170, 161, 174),
	Accent = Color3.fromRGB(112, 18, 67),
	Pink = Color3.fromRGB(237, 132, 185),
	Success = Color3.fromRGB(172, 211, 194),
	Error = Color3.fromRGB(244, 157, 167),
}

end

Modules["Surface"] = function(require)
local Theme = require("./Theme")

--//Variables
local Surface = {}

--//Source
function Surface.Create(Class, Properties, Parent)
	local Object = Instance.new(Class)
	for Name, Value in pairs(Properties) do Object[Name] = Value end
	Object.Parent = Parent
	return Object
end

function Surface.Config(Options)
	local Config = table.clone(Options or {})
	Config.Name = Config.Name or "YHubStartup"
	Config.Discord = Config.Discord or "https://discord.gg/53J4h36DtX"
	Config.Theme = setmetatable(table.clone(Config.Theme or {}), { __index = Theme })
	return Config
end

function Surface.Mount(Gui)
	local function Mount(Parent)
		if typeof(Parent) ~= "Instance" then return false end
		return pcall(function()
			local Previous = Parent:FindFirstChild(Gui.Name)
			if Previous then Previous:Destroy() end
			Gui.Parent = Parent
		end)
	end
	local Success, Hidden = pcall(function() return type(gethui) == "function" and gethui() end)
	if Success and Mount(Hidden) then return end
	if Mount(game:GetService("CoreGui")) then return end
	local Player = game:GetService("Players").LocalPlayer
	assert(Player and Mount(Player:WaitForChild("PlayerGui", 5)), "Y Hub UI is unavailable")
end

function Surface.Animate(Object, Properties, Duration, Repeats, Reverses)
	local Tween = game:GetService("TweenService"):Create(Object,
		TweenInfo.new(Duration or 0.3, Enum.EasingStyle.Quad, Enum.EasingDirection.Out, Repeats or 0, Reverses or false), Properties)
	Tween:Play()
	return Tween
end

return Surface

end

Modules["Progress"] = function(require)
local Surface = require("./Surface")

--//Variables
local Progress = {}
Progress.__index = Progress
local Create = Surface.Create

--//Source
function Progress.new(Options)
	local self = setmetatable({ Config = Surface.Config(Options), Connections = {}, Tweens = {}, Stage = 0 }, Progress)
	local Success, Message = pcall(self.Build, self)
	if not Success then self:Destroy() error(Message, 0) end
	return self
end

function Progress:Connect(Signal, Callback)
	self.Connections[#self.Connections + 1] = Signal:Connect(Callback)
end

function Progress:Animate(Key, Object, Properties, Duration, Repeats, Reverses)
	if self.Tweens[Key] then self.Tweens[Key]:Cancel() end
	self.Tweens[Key] = Surface.Animate(Object, Properties, Duration, Repeats, Reverses)
end

function Progress:Build()
	local Theme = self.Config.Theme
	local Gui = Create("ScreenGui", {
		Name = self.Config.Name, ResetOnSpawn = false, DisplayOrder = 10001,
		ZIndexBehavior = Enum.ZIndexBehavior.Sibling, ScreenInsets = Enum.ScreenInsets.CoreUISafeInsets,
	})
	self.Gui = Gui
	Surface.Mount(Gui)
	self.Layout = Create("Frame", { Name = "Layout", Size = UDim2.fromScale(1, 1), BackgroundTransparency = 1 }, Gui)
	local Panel = Create("CanvasGroup", {
		Name = "Panel", AnchorPoint = Vector2.new(0.5, 1), Position = UDim2.new(0.5, 0, 1, 0),
		Size = UDim2.fromOffset(356, 184), BackgroundColor3 = Theme.Background, BorderSizePixel = 0,
		GroupTransparency = 1,
	}, self.Layout)
	self.Panel = Panel
	Create("UICorner", { CornerRadius = UDim.new(0, 6) }, Panel)
	Create("UIStroke", { Color = Theme.Border, Thickness = 1 }, Panel)
	self.Scroll = Create("ScrollingFrame", {
		Name = "Content", Size = UDim2.fromScale(1, 1), BackgroundTransparency = 1, BorderSizePixel = 0,
		CanvasSize = UDim2.fromOffset(0, 184), ScrollBarThickness = 2,
		ScrollBarImageColor3 = Theme.Pink, ScrollingDirection = Enum.ScrollingDirection.Y,
	}, Panel)
	local function Label(Name, Text, Position, Size, TextSize, Color, Font)
		return Create("TextLabel", {
			Name = Name, Text = Text, Position = Position, Size = Size, BackgroundTransparency = 1,
			TextColor3 = Color, Font = Font or Enum.Font.Gotham, TextSize = TextSize,
			TextXAlignment = Enum.TextXAlignment.Left, TextWrapped = true,
		}, self.Scroll)
	end
	local Mark = Label("Mark", "<i>Y</i>", UDim2.fromOffset(18, 17), UDim2.fromOffset(30, 30), 22, Theme.Text, Enum.Font.GothamBold)
	Mark.RichText, Mark.BackgroundTransparency, Mark.BackgroundColor3, Mark.TextXAlignment = true, 0, Theme.Accent, Enum.TextXAlignment.Center
	self.Mark = Mark
	self.Brand = Label("Brand", "Y HUB.", UDim2.fromOffset(59, 17), UDim2.new(1, -110, 0, 30), 17, Theme.Text, Enum.Font.GothamBold)
	local Close = Create("TextButton", {
		Name = "Close", Text = utf8.char(215), Position = UDim2.new(1, -50, 0, 8), Size = UDim2.fromOffset(44, 44),
		BackgroundTransparency = 1, TextColor3 = Theme.Muted, TextSize = 23, Font = Enum.Font.Gotham,
	}, self.Scroll)
	self.Title = Label("Title", "Starting up", UDim2.fromOffset(18, 61), UDim2.new(1, -36, 0, 25), 15, Theme.Text, Enum.Font.GothamMedium)
	local Track = Create("Frame", {
		Name = "Track", Position = UDim2.fromOffset(18, 102), Size = UDim2.new(1, -36, 0, 3),
		BackgroundColor3 = Theme.Border, BorderSizePixel = 0,
	}, self.Scroll)
	self.Track = Track
	self.Fill = Create("Frame", { Name = "Fill", Size = UDim2.fromScale(0, 1), BackgroundColor3 = Theme.Pink, BorderSizePixel = 0 }, Track)
	self.Hint = Label("Hint", "Community", UDim2.fromOffset(18, 126), UDim2.new(1, -158, 0, 44), 12, Theme.Muted)
	local Discord = Create("TextButton", {
		Name = "Discord", Text = "Discord " .. utf8.char(8599), Position = UDim2.new(1, -136, 0, 126), Size = UDim2.fromOffset(118, 44),
		BackgroundColor3 = Theme.Surface, BackgroundTransparency = 0, BorderSizePixel = 0, AutoButtonColor = false,
		TextColor3 = Theme.Pink, TextSize = 13, Font = Enum.Font.GothamMedium,
	}, self.Scroll)
	Create("UICorner", { CornerRadius = UDim.new(0, 4) }, Discord)
	Create("UIStroke", { Color = Theme.Border, Thickness = 1, ApplyStrokeMode = Enum.ApplyStrokeMode.Border }, Discord)
	self.Discord = Discord
	self.Invite = Create("TextBox", {
		Name = "Invite", Text = self.Config.Discord, Visible = false, ClearTextOnFocus = false, TextEditable = false,
		Position = UDim2.fromOffset(18, 174), Size = UDim2.new(1, -36, 0, 44),
		BackgroundColor3 = Theme.Surface, BorderSizePixel = 0, TextColor3 = Theme.Text, TextSize = 11, Font = Enum.Font.Gotham,
	}, self.Scroll)
	self:Connect(Close.Activated, function() self:Destroy() end)
	self:Connect(Discord.Activated, function() self:CopyInvite() end)
	self:Connect(Discord.MouseEnter, function() self:Animate("Discord", Discord, { BackgroundColor3 = Theme.Accent }, 0.2) end)
	self:Connect(Discord.MouseLeave, function() self:Animate("Discord", Discord, { BackgroundColor3 = Theme.Surface }, 0.2) end)
	self:Connect(self.Layout:GetPropertyChangedSignal("AbsoluteSize"), function() self:Resize() end)
	self:Connect(Gui.Destroying, function() self:Destroy() end)
	self:Resize()
	self:Animate("Entrance", Panel, { GroupTransparency = 0, Position = UDim2.new(0.5, 0, 1, -16) }, 0.38)
	self:Animate("Activity", self.Fill, { BackgroundTransparency = 0.4 }, 0.8, -1, true)
end

function Progress:Resize()
	if self.Destroyed then return end
	local Size = self.Layout.AbsoluteSize
	if Size.X < 1 or Size.Y < 1 then return end
	local Height = self.Compact and 70 or (self.Invite.Visible and 232 or 184)
	self.Scroll.CanvasSize = UDim2.fromOffset(0, Height)
	self.Panel.Size = UDim2.fromOffset(math.min(356, math.max(1, Size.X - 24)), math.min(Height, math.max(1, Size.Y - 24)))
end

function Progress:StopActivity()
	for _, Key in ipairs({ "Activity", "Sweep" }) do
		if self.Tweens[Key] then self.Tweens[Key]:Cancel() self.Tweens[Key] = nil end
	end
end

function Progress:StartActivity()
	self:StopActivity()
	self.Fill.BackgroundTransparency = 0
	self.Fill.Position = UDim2.fromScale(0, 0)
	if self.Compact then
		self.Fill.Size = UDim2.fromScale(0.24, 1)
		self:Animate("Sweep", self.Fill, { Position = UDim2.fromScale(0.76, 0) }, 1.2, -1, true)
	end
	self:Animate("Activity", self.Fill, { BackgroundTransparency = 0.4 }, 0.8, -1, true)
end

function Progress:SetCompact(Compact)
	self.Compact = Compact
	self.Gui.DisplayOrder = Compact and 9999 or 10001
	self.Brand.Visible, self.Hint.Visible, self.Discord.Visible = not Compact, not Compact, not Compact
	self.Invite.Visible = false
	self.Title.Position = Compact and UDim2.fromOffset(60, 19) or UDim2.fromOffset(18, 61)
	self.Title.Size = Compact and UDim2.new(1, -116, 0, 25) or UDim2.new(1, -36, 0, 25)
	self.Track.Position = UDim2.fromOffset(18, Compact and 56 or 102)
	self:Resize()
end

function Progress:BeginLoading(Message)
	if self.Destroyed or self.Resolved then return end
	if self.Tweens.Fill then self.Tweens.Fill:Cancel() self.Tweens.Fill = nil end
	self:SetCompact(true)
	self.Title.Text = Message or "Loading Y Hub"
	self:StartActivity()
	if self.Watching then return end
	self.Watching = true
	-- Keep UI cleanup on the original UI thread, including after native game calls.
	task.spawn(function()
		while not self.Destroyed and not self.Resolved do
			if not self.CompletionRequested and self.ReadyProbe then
				local Checked, Ready = pcall(self.ReadyProbe)
				if Checked and Ready == true then self:RequestComplete(true) end
			end
			if self.CompletionRequested then
				local Completed = pcall(self.ApplyCompletion, self, self.CompletionResult)
				if not Completed then self:Destroy() end
				break
			end
			task.wait(0.2)
		end
		self.ReadyProbe = nil
		self.Watching = false
	end)
end

function Progress:RequestComplete(Success)
	if self.Destroyed or self.Completed or self.CompletionRequested then return end
	self.CompletionResult = Success
	self.CompletionRequested = true
end

function Progress:SetLoadingVisible(Visible, Message)
	if self.Destroyed or self.Resolved then return end
	if Message then self.Title.Text = Message end
	self.Gui.Enabled = Visible
	if Visible then self:StartActivity() else self:StopActivity() end
end

function Progress:Complete(Success)
	if self.Watching then self:RequestComplete(Success) return end
	self:ApplyCompletion(Success)
end

function Progress:ApplyCompletion(Success)
	if self.Destroyed or self.Completed then return end
	self.Completed = true
	if Success == nil then self:Destroy() return end
	self.Gui.Enabled = true
	if not Success then self:SetCompact(false) end
	self:SetResult(Success, Success and "Ready" or "Unable to load Y Hub")
	if Success then
		task.delay(0.45, function()
			if not self.Destroyed then self:Dismiss() end
		end)
	end
end

function Progress:CopyInvite()
	if self.Destroyed or self.InviteCopied then return end
	local Clipboard = self.Config.CopyInvite or setclipboard or toclipboard
	local Success = type(Clipboard) == "function" and pcall(Clipboard, self.Config.Discord)
	if not Success then
		self.Invite.Visible = true
		self:Resize()
		self.Invite:CaptureFocus()
		self.Invite.SelectionStart, self.Invite.CursorPosition = 1, #self.Invite.Text + 1
		return
	end
	self.InviteCopied = true
	self.Discord.Text, self.Discord.TextColor3 = "Invite copied", self.Config.Theme.Success
	task.delay(2, function()
		if self.Destroyed then return end
		self.InviteCopied = false
		self.Discord.Text, self.Discord.TextColor3 = "Discord " .. utf8.char(8599), self.Config.Theme.Pink
	end)
end

function Progress:WaitForEntry()
	task.wait(0.4)
	return not self.Destroyed
end

function Progress:SetStage(Index, Message)
	if self.Destroyed or self.Resolved then return end
	self.Stage = math.max(self.Stage, math.clamp(Index, 1, 3))
	self.Title.Text = Message or (self.Stage == 1 and "Starting up" or "Checking compatibility")
	self:Animate("Fill", self.Fill, { Size = UDim2.fromScale(({ 0.16, 0.48, 0.8 })[self.Stage], 1) }, 0.38)
end

function Progress:SetResult(Success, Message)
	if self.Destroyed or self.Resolved then return end
	self.Resolved = true
	self.Title.Text = Message or (Success and "Ready" or "Executor not supported")
	self.Title.TextColor3 = Success and self.Config.Theme.Success or self.Config.Theme.Error
	self.Hint.Text = Success and "Community" or "Need help?"
	self:StopActivity()
	self.Fill.Position = UDim2.fromScale(0, 0)
	self.Fill.BackgroundTransparency = 0
	self.Fill.BackgroundColor3 = self.Title.TextColor3
	self:Animate("Fill", self.Fill, { Size = UDim2.fromScale(1, 1) }, 0.4)
end

function Progress:Dismiss()
	if self.Destroyed then return false end
	self:Animate("Entrance", self.Panel, { GroupTransparency = 1, Position = UDim2.new(0.5, 0, 1, 0) }, 0.25)
	task.wait(0.25)
	if self.Destroyed then return false end
	self:Destroy()
	return true
end

function Progress:Destroy()
	if self.Destroyed then return end
	self.Destroyed = true
	self.ReadyProbe = nil
	for _, Connection in ipairs(self.Connections) do Connection:Disconnect() end
	for _, Tween in pairs(self.Tweens) do Tween:Cancel() end
	table.clear(self.Connections)
	table.clear(self.Tweens)
	if self.Gui then self.Gui:Destroy() end
end

return Progress

end

Modules["init"] = function(require)
local Progress = require("./Progress")

return {
	Version = "1.1.2",
	CreateProgress = Progress.new,
}

end

local function Import(Path)
	local Name = string.gsub(Path, "^%./", "")
	if Loaded[Name] == nil then Loaded[Name] = assert(Modules[Name], "Unknown UI module")(Import) end
	return Loaded[Name]
end
return Import("init")

end)()
local StartupCompatibility = (function()
--//Variables
local Compatibility = {}
local Required = {
	"loadstring", "getgenv", "getgc", "getrawmetatable",
	"hookmetamethod", "getnamecallmethod", "hookfunction", "newcclosure",
}

--//Source
local function Resolve(Environment)
	local ExecutorEnvironment
	if type(Environment.getgenv) == "function" then
		local Success, Value = pcall(Environment.getgenv)
		if Success and type(Value) == "table" then ExecutorEnvironment = Value end
	end
	return setmetatable({}, { __index = function(_, Name)
		local Value = Environment[Name]
		if Value ~= nil then return Value end
		return ExecutorEnvironment and ExecutorEnvironment[Name]
	end })
end

function Compatibility.GetRequest(Environment)
	local Functions = Resolve(Environment)
	for _, Candidate in pairs({ Functions.request, Functions.http_request,
		type(Functions.http) == "table" and Functions.http.request, type(Functions.syn) == "table" and Functions.syn.request }) do
		if type(Candidate) == "function" then return Candidate end
	end
	return nil
end

function Compatibility.Check(Environment, OnStage)
	local Result = { Supported = false, Executor = "Unknown executor", Missing = {}, Failed = {} }
	local Functions = Resolve(Environment)
	local function Stage(Index, Message)
		if OnStage then OnStage(Index, Message) end
	end
	Stage(1, "Identifying your executor...")
	local Identify = Functions.identifyexecutor or Functions.getexecutorname
	if type(Identify) == "function" then
		local Success, Name = pcall(Identify)
		if Success and type(Name) == "string" and #Name > 0 then Result.Executor = string.sub(Name, 1, 60) end
	end
	Stage(2, "Checking required functions...")
	for _, Name in ipairs(Required) do
		if type(Functions[Name]) ~= "function" then Result.Missing[#Result.Missing + 1] = Name end
	end
	if not Compatibility.GetRequest(Environment) then Result.Missing[#Result.Missing + 1] = "request" end
	if #Result.Missing > 0 then return Result end

	Stage(3, "Verifying function behavior...")
	-- Runtime compilation keeps these disposable test functions outside obfuscator VMs.
	local Success = pcall(function()
		local Factory = assert(Functions.loadstring("return function(value) return value + 1 end, function(value) return value + 100 end"))
		local Target, Replacement = Factory()
		assert(type(Target) == "function" and type(Replacement) == "function")
		local Wrapped = Functions.newcclosure(Target)
		assert(type(Wrapped) == "function" and Wrapped(7) == 8)
		local References = { Target }
		local Original = Functions.hookfunction(Target, Replacement)
		local Hooked = References[1](7) == 107
		local Preserved = type(Original) == "function" and Original(7) == 8
		if Hooked and type(Original) == "function" then
			if type(Functions.restorefunction) == "function" then
				Functions.restorefunction(Target)
			else
				Functions.hookfunction(Target, Original)
			end
			assert(References[1](7) == 8)
		end
		assert(Hooked and Preserved)
	end)
	if not Success then Result.Failed[1] = "function hooks" end
	Result.Supported = #Result.Failed == 0
	return Result
end

return Compatibility

end)()
local StartupPreflight = (function(require)
local Compatibility = require("./Compatibility")

--//Variables
local Preflight = {}
local Endpoint = "https://useyhub.com/api/v1/catalog"
local RegistryUrl = "https://raw.githubusercontent.com/GodErste/Y-Core/main/games/index.lua"

--//Source
function Preflight.GetGame(Registry, PlaceId, ExpectedGame)
	local GameId = Registry.FindByPlaceId(PlaceId)
	if not GameId or (ExpectedGame and Registry.NormalizeGameId(ExpectedGame) ~= GameId) then return nil end
	return GameId
end

local function Fetch(Environment, Url, Cancelled, Failure)
	local Request = Compatibility.GetRequest(Environment)
	if type(Request) ~= "function" then return nil, "Connection failed" end
	local Active, Done, Body, Message = true, false, nil, "Connection failed"
	local Deadline = os.clock() + 6
	task.spawn(function()
		local Success, Response = pcall(Request, {
			Url = Url, Method = "GET", Headers = { ["Cache-Control"] = "no-cache" },
		})
		if not Active or Cancelled() then return end
		if Success and type(Response) == "table" then
			local Code = tonumber(Response.StatusCode)
			Message = Code == 429 and "Service busy" or Failure
			if Code == 200 and type(Response.Body) == "string" and #Response.Body <= 65536 then
				Body = Response.Body
			end
		end
		Done = true
	end)
	while not Done and os.clock() < Deadline and not Cancelled() do task.wait(0.05) end
	Active = false
	if Cancelled() then return nil, "cancelled" end
	if not Done then return nil, "Connection timed out" end
	return Body, Message
end

function Preflight.LoadRegistry(Environment, Cancelled)
	if not Compatibility.GetRequest(Environment) then return nil, "Executor not supported" end
	local Source, Message = Fetch(Environment, RegistryUrl, Cancelled, "Game list unavailable")
	if not Source then return nil, Message end
	local Success, Registry = pcall(function()
		local Chunk = assert(loadstring(Source, "@YHub.GameRegistry"))
		local Value = Chunk()
		assert(type(Value) == "table" and type(Value.Games) == "table")
		for _, Method in ipairs({ "FindByPlaceId", "NormalizeGameId", "GetGame" }) do
			assert(type(Value[Method]) == "function")
		end
		return Value
	end)
	if Success then return Registry end
	return nil, "Game list unavailable"
end

function Preflight.CheckWebsite(Environment, Cancelled)
	local Source, Message = Fetch(Environment, Endpoint, Cancelled, "Website unavailable")
	if not Source then return false, Message end
	local Parsed, Body = pcall(function() return game:GetService("HttpService"):JSONDecode(Source) end)
	local Available = Parsed and type(Body) == "table" and type(Body.games) == "table" and type(Body.sales) == "table"
	if Available then return true end
	return false, "Website unavailable"
end

return Preflight

end)(function(Name)
    if Name == "./Compatibility" then return StartupCompatibility end
    error("Unknown preflight module")
end)
local Startup = (function(require)
local Compatibility = require("./Compatibility")
local Preflight = require("./Preflight")
local UI = require("./UI")

--//Variables
-- Existing builds can consume this handoff; new preflight reuse also requires the fields below.
local Bootstrap = { Version = 1 }

--//Source
function Bootstrap.Run(Inherited, ExpectedGame)
	local PlaceId = game.PlaceId
	local Registry = type(Inherited) == "table" and Inherited.Registry
	local GameId = Registry and Preflight.GetGame(Registry, PlaceId, ExpectedGame)
	if GameId and type(Inherited) == "table" and Inherited.Supported == true and Inherited.Handoff == true
		and Inherited.GameId == GameId and Inherited.PlaceId == PlaceId and Inherited.WebsiteReady == true
		and Inherited.Version == Bootstrap.Version and type(Inherited.CheckedAt) == "number"
		and os.clock() >= Inherited.CheckedAt and os.clock() - Inherited.CheckedAt < 90 then
		Inherited.Handoff = false
		return Inherited
	end
	local Success, Screen = pcall(UI.CreateProgress)
	if not Success then
		warn("[Y Hub] Startup interface could not open.")
		return nil
	end
	if not Screen:WaitForEntry() then return nil end
	Screen:SetStage(1, "Checking game")
	local Message
	Registry, Message = Preflight.LoadRegistry(getfenv(), function() return Screen.Destroyed end)
	if Screen.Destroyed then return nil end
	if not Registry then
		Screen:SetResult(false, Message)
		warn("[Y Hub] " .. Message)
		return nil
	end
	GameId = Preflight.GetGame(Registry, PlaceId, ExpectedGame)
	if not GameId then
		Screen:SetResult(false, "Game not supported")
		warn("[Y Hub] Game not supported: " .. tostring(PlaceId))
		return nil
	end
	local Finished = false
	task.delay(8, function()
		if not Finished and not Screen.Destroyed then
			Screen:SetResult(false, "Check timed out")
			Finished = true
		end
	end)
	local Checked, Result = pcall(Compatibility.Check, getfenv(), function(Index)
		assert(not Finished and not Screen.Destroyed, "Startup cancelled")
		Screen:SetStage(Index)
		task.wait(0.4)
	end)
	if Finished or Screen.Destroyed then return nil end
	Finished = true
	if not Checked then
		Screen:SetResult(false, "Unable to continue")
		warn("[Y Hub] Executor compatibility check failed.")
		return nil
	end
	if not Result.Supported then
		Screen:SetResult(false)
		warn("[Y Hub] Unsupported executor: " .. Result.Executor .. "; " .. table.concat(Result.Missing, ", ") .. table.concat(Result.Failed, ", "))
		return nil
	end
	Screen:SetStage(3, "Connecting to Y Hub")
	local Available, Message = Preflight.CheckWebsite(getfenv(), function() return Screen.Destroyed end)
	if Screen.Destroyed then return nil end
	if not Available then
		Screen:SetResult(false, Message)
		warn("[Y Hub] " .. Message)
		return nil
	end
	Screen:BeginLoading("Loading Y Hub")
	Result.Version, Result.CheckedAt, Result.Handoff = Bootstrap.Version, os.clock(), true
	Result.GameId, Result.PlaceId, Result.WebsiteReady = GameId, PlaceId, true
	Result.Presentation = Screen
	Result.Registry = Registry
	return Result
end

return Bootstrap

end)(function(Name)
    if Name == "./Compatibility" then return StartupCompatibility end
    if Name == "./Preflight" then return StartupPreflight end
    if Name == "./UI" then return StartupUI end
    error("Unknown startup module")
end)

local startupResult = Startup.Run()
if not startupResult then return nil end
LoadingPresentation = startupResult.Presentation

--//Y Hub Loader
-- Release: loadstring(game:HttpGet("https://raw.githubusercontent.com/GodErste/Y-Core/main/loader.lua"))()
-- Local dev: getgenv().YHubLoaderConfig = { BaseUrl = "http://127.0.0.1:8124/", Game = "bridger", SourceMode = true, ForceReload = true }

--//Variables
local globalEnvironment = (getgenv and getgenv()) or _G
local loaderConfig = globalEnvironment.YHubLoaderConfig
	or globalEnvironment.YCoreLoaderConfig
	or globalEnvironment.YAutoSignalLoaderConfig
	or {}
local baseEnvironment = (getfenv and getfenv()) or _G
local baseUrl = loaderConfig.BaseUrl or "https://raw.githubusercontent.com/GodErste/Y-Core/main/"
local verbose = loaderConfig.Verbose == true
local automaticCacheBust = tostring(math.floor(os.clock() * 1000000))

local function releaseDiagnosticsEnabled()
	return loaderConfig.ReleaseDiagnostics == true
		or loaderConfig.BridgerReleaseDiagnostics == true
		or loaderConfig.Verbose == true
end

local function getExecutorName()
	local getter = nil

	if type(identifyexecutor) == "function" then
		getter = identifyexecutor
	elseif type(getexecutorname) == "function" then
		getter = getexecutorname
	end

	if type(getter) ~= "function" then
		return ""
	end

	local success, name = pcall(getter)
	return success and tostring(name or "") or ""
end

local detectedExecutorName = getExecutorName()

local function isPotassiumExecutor()
	return string.find(string.lower(detectedExecutorName), "potassium", 1, true) ~= nil
end

local function callable(callback)
	if type(callback) == "function" then
		return callback
	end

	if type(callback) == "table" then
		local target = callback
		local failed = false

		return function(...)
			if failed then
				return nil
			end

			local success, first, second, third, fourth, fifth, sixth, seventh, eighth = pcall(target, ...)
			if not success then
				failed = true
				return nil
			end

			return first, second, third, fourth, fifth, sixth, seventh, eighth
		end
	end

	return function() end
end

local function identity(callback)
	return callable(callback)
end

local function attribute()
	return nil
end

local function ensureFunction(environment, name, fallback)
	if type(environment[name]) ~= "function" then
		environment[name] = fallback
	end

	return environment[name]
end

local function shouldInstallNewcclosureCompatibility()
	if loaderConfig.DisableNewcclosureCompat == true then
		return false, "disabled-config"
	end

	if loaderConfig.EnableNewcclosureCompat == true then
		return true, "enabled-config"
	end

	if isPotassiumExecutor() then
		return false, "potassium"
	end

	return true, "default"
end

local function installNewcclosureCompatibility()
	local key = "__YHubNewcclosureCompat"
	local state = rawget(globalEnvironment, key) or rawget(baseEnvironment, key)
	local native = type(state) == "table" and type(state.Native) == "function" and state.Native or nil

	if type(native) ~= "function" and type(newcclosure) == "function" then
		native = newcclosure
	end

	if type(native) ~= "function" then
		return
	end

	local proxy = function(callback)
		local normalized = callable(callback)
		local success, closure = pcall(native, normalized)

		if success and type(closure) == "function" then
			return closure
		end

		return normalized
	end

	state = {
		Native = native,
		Proxy = proxy,
	}

	pcall(function()
		globalEnvironment[key] = state
		globalEnvironment["newcclosure"] = proxy
	end)
	pcall(function()
		baseEnvironment[key] = state
		baseEnvironment["newcclosure"] = proxy
	end)
end

ensureFunction(globalEnvironment, "LPH_ATTRIBUTES", attribute)
ensureFunction(globalEnvironment, "VM", attribute)
ensureFunction(globalEnvironment, "PRESET", attribute)
ensureFunction(globalEnvironment, "NONE", attribute)
ensureFunction(globalEnvironment, "FAST", attribute)
globalEnvironment["YHUB_NO_VIRTUALIZE"] = identity
ensureFunction(baseEnvironment, "LPH_ATTRIBUTES", globalEnvironment["LPH_ATTRIBUTES"])
ensureFunction(baseEnvironment, "VM", globalEnvironment["VM"])
ensureFunction(baseEnvironment, "PRESET", globalEnvironment["PRESET"])
ensureFunction(baseEnvironment, "NONE", globalEnvironment["NONE"])
ensureFunction(baseEnvironment, "FAST", globalEnvironment["FAST"])
baseEnvironment["YHUB_NO_VIRTUALIZE"] = globalEnvironment["YHUB_NO_VIRTUALIZE"]

local installNewcclosureCompat, newcclosureCompatReason = shouldInstallNewcclosureCompatibility()
if installNewcclosureCompat then
	installNewcclosureCompatibility()
end

if baseUrl:sub(-1) ~= "/" then
	baseUrl = baseUrl .. "/"
end

local Framework = {
	Name = "Y Hub",
	Version = "0.1.0",
	BaseUrl = baseUrl,
	Cache = {},
	Config = loaderConfig,
	Startup = startupResult,
	StartedAt = os.clock(),
}
ObserveLoading(Framework)

function Framework:Trace() end

globalEnvironment.YHubFramework = Framework
globalEnvironment.YCoreFramework = Framework

--//Source
local function log(message)
	if verbose then
		print("[Y Hub] " .. tostring(message))
	end
end

local function fail(message)
	FinishLoading(false)
	warn("[Y Hub] framework start failed: " .. tostring(message))
	return nil
end

local function normalizeModulePath(modulePath)
	return tostring(modulePath or ""):gsub("\\", "/"):gsub("^/+", "")
end

local function cacheBust()
	if loaderConfig.CacheBust ~= nil then
		return tostring(loaderConfig.CacheBust)
	end

	return automaticCacheBust
end

local function withCacheBust(url)
	if loaderConfig.NoCacheBust == true then
		return url
	end

	local separator = string.find(url, "?", 1, true) and "&" or "?"
	return url .. separator .. "v=" .. cacheBust()
end

local function loadLua(source, chunkName)
	local loadedChunk, errorMessage = loadstring(source, chunkName)
	assert(loadedChunk, errorMessage)
	return loadedChunk
end

local function setChunkEnvironment(loadedChunk, moduleEnvironment)
	if setfenv then
		setfenv(loadedChunk, moduleEnvironment)
	end

	return loadedChunk
end

function Framework:Fetch(modulePath)
	modulePath = normalizeModulePath(modulePath)
	local moduleUrl = withCacheBust(self.BaseUrl .. modulePath)

	log("fetch " .. moduleUrl)
	return game:HttpGet(moduleUrl)
end

function Framework:FetchUrl(url)
	url = withCacheBust(tostring(url))

	log("fetch " .. url)
	return game:HttpGet(url)
end

local function loadBootstrapModule(modulePath)
	local moduleSource = Framework:Fetch(modulePath)
	local loadedChunk = loadLua(moduleSource, "@" .. modulePath)
	local moduleEnvironment = setmetatable({
		Framework = Framework,
		yrequire = function(childModulePath, childForceReload)
			return Framework:yrequire(childModulePath, childForceReload)
		end,
	}, {
		__index = baseEnvironment,
	})

	moduleEnvironment.Require = moduleEnvironment.yrequire
	return setChunkEnvironment(loadedChunk, moduleEnvironment)()
end

do
	local assertSuccess, assertModule = pcall(function()
		return loadBootstrapModule("shared/Framework/Assert.lua")
	end)

	if assertSuccess and type(assertModule) == "table" and type(assertModule.Attach) == "function" then
		assertModule.Attach(Framework)
	else
		warn("[Y Hub] Assert bootstrap failed: " .. tostring(assertModule))
	end
end

if type(Framework.ReportError) ~= "function" then
	function Framework:ReportError(stage, errorObject)
		return tostring(errorObject)
	end
end
if type(Framework.StartErrorWatcher) ~= "function" then
	function Framework:StartErrorWatcher()
		return false
	end
end

local function runWithErrorReport(framework, stage, details, callback)
	if framework and type(framework.RunWithErrorReport) == "function" then
		return framework:RunWithErrorReport(stage, details, callback)
	end

	local success, result = xpcall(callback, function(errorObject)
		return framework:ReportError(stage, errorObject, details)
	end)

	if not success then
		error(result, 0)
	end

	return result
end

function Framework:LoadUrl(url, chunkName)
	local resolvedChunkName = chunkName or ("@" .. tostring(url))
	local moduleSource = runWithErrorReport(self, "fetch-url", {
		url = url,
		chunk = resolvedChunkName,
	}, function()
		return self:FetchUrl(url)
	end)
	local loadedChunk = runWithErrorReport(self, "compile-url", {
		url = url,
		chunk = resolvedChunkName,
	}, function()
		return loadLua(moduleSource, resolvedChunkName)
	end)

	local moduleEnvironment = setmetatable({
		Framework = self,
		yrequire = function(childModulePath, childForceReload)
			return self:yrequire(childModulePath, childForceReload)
		end,
	}, {
		__index = baseEnvironment,
	})

	moduleEnvironment.Require = moduleEnvironment.yrequire

	return runWithErrorReport(self, "execute-url", {
		url = url,
		chunk = resolvedChunkName,
	}, function()
		return setChunkEnvironment(loadedChunk, moduleEnvironment)()
	end)
end

function Framework:yrequire(modulePath, forceReload)
	modulePath = normalizeModulePath(modulePath)

	if not forceReload and self.Cache[modulePath] ~= nil then
		return self.Cache[modulePath]
	end

	local moduleSource = runWithErrorReport(self, "fetch-module", {
		module = modulePath,
	}, function()
		return self:Fetch(modulePath)
	end)
	local loadedChunk = runWithErrorReport(self, "compile-module", {
		module = modulePath,
	}, function()
		return loadLua(moduleSource, "@" .. modulePath)
	end)

	local moduleEnvironment = setmetatable({
		Framework = self,
		yrequire = function(childModulePath, childForceReload)
			return self:yrequire(childModulePath, childForceReload)
		end,
	}, {
		__index = baseEnvironment,
	})

	moduleEnvironment.Require = moduleEnvironment.yrequire

	local moduleResult = runWithErrorReport(self, "execute-module", {
		module = modulePath,
	}, function()
		return setChunkEnvironment(loadedChunk, moduleEnvironment)()
	end)
	if moduleResult == nil then
		moduleResult = true
	end

	self.Cache[modulePath] = moduleResult
	return moduleResult
end

Framework.Require = Framework.yrequire

if Framework.Release ~= true or releaseDiagnosticsEnabled() then
	Framework:StartErrorWatcher()
end

function Framework:Start()
	--> Load selected game
	local startSuccess, startResult = xpcall(function()
		local gameRegistry = assert(self.Startup.Registry, "Game list unavailable")
		local selectedGameId = self.Startup.GameId
		if selectedGameId == nil then error("Game not supported") end
		selectedGameId = tostring(selectedGameId):lower()
		if type(gameRegistry.NormalizeGameId) == "function" then
			selectedGameId = gameRegistry.NormalizeGameId(selectedGameId)
		end

		local gameInfo = nil
		if type(gameRegistry.GetGame) == "function" then
			gameInfo = gameRegistry.GetGame(selectedGameId)
		elseif type(gameRegistry.Games) == "table" then
			gameInfo = gameRegistry.Games[selectedGameId]
		end

		if type(gameInfo) ~= "table" then
			error("unknown game: " .. selectedGameId)
		end

		self.GameId = selectedGameId
		self.Game = gameInfo
		self.Name = gameInfo.Name or self.Name
		self.Version = tostring(gameInfo.Version or self.Version)

		local sourceMode = self.Config.SourceMode == true
		local gameModule
		if self.Startup.Presentation then
			self.Startup.Presentation:SetLoadingVisible(true, sourceMode and "Starting Y Hub" or "Loading Luarmor")
		end

		if sourceMode then
			local gameModulePath = gameInfo.Entry or ("games/" .. selectedGameId .. "/init.lua")
			gameModule = self:yrequire(gameModulePath, self.Config.ForceReload == true)
		else
			local bundleUrl = gameInfo.BundleUrl or gameInfo.BuildUrl or gameInfo.LoaderUrl

			if bundleUrl then
				gameModule = self:LoadUrl(bundleUrl, "@" .. selectedGameId .. ".bundle")
			elseif gameInfo.Loader then
				gameModule = self:yrequire(gameInfo.Loader, self.Config.ForceReload == true)
			else
				error("missing bundle url for game: " .. selectedGameId)
			end
		end

		if type(gameModule) == "table" and type(gameModule.Start) == "function" then
			local result = gameModule.Start(self)
			return result
		end

		return gameModule
	end, function(errorObject)
		return self:ReportError("framework-start", errorObject, {
			game = self.GameId or self.Config.Game or "auto",
		})
	end)

	if not startSuccess then
		return fail(startResult)
	end

	return startResult
end

return Framework:Start()

end
local Loaded, Result = pcall(RunHub)
if LoadingPresentation then
    local Outcome = Loaded and Result ~= false
    if Loaded and Result == nil then Outcome = nil end
    FinishLoading(Outcome)
end
if not Loaded then error(Result, 0) end
return Result
